slice_name: Average and Sum Trends
description: null
certified_by: null
certification_details: null
viz_type: dual_line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric:
    aggregate: AVG
    column:
      column_name: num
      type: BIGINT(20)
    expressionType: SIMPLE
    label: AVG(num)
    optionName: metric_vgops097wej_g8uff99zhk7
  metric_2: sum__num
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 10000000
  time_range: '100 years ago : now'
  viz_type: dual_line
query_context: null
cache_timeout: null
uuid: 952e9411-619f-4c7a-aee1-522a24ca39b2
version: 1.0.0
dataset_uuid: b04f2fc3-ef74-44e8-9bd8-d1896ab9e59c
