slice_name: Birth in France by department in 2016
description: null
certified_by: null
certification_details: null
viz_type: country_map
params:
  entity: DEPT_ID
  granularity_sqla: ''
  metric:
    aggregate: AVG
    column:
      column_name: '2004'
      type: INT
    expressionType: SIMPLE
    label: Boys
    optionName: metric_112342
  row_limit: 500000
  select_country: france
  since: ''
  until: ''
  viz_type: country_map
query_context: null
cache_timeout: null
uuid: ab5d9fb5-38c5-49e0-a481-580e6052b5d2
version: 1.0.0
dataset_uuid: cddc1903-f831-4930-91f5-a1bccce25cb3
