slice_name: Growth Rate
description: null
certified_by: null
certification_details: null
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  num_period_compare: '10'
  row_limit: 10000000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: line
query_context: null
cache_timeout: null
uuid: 2463a916-d9be-4ea9-9a1b-197ba61b17ce
version: 1.0.0
dataset_uuid: a430d917-f805-4fff-acb2-19135fa7b154
