slice_name: Mapbox Long/Lat
description: null
certified_by: null
certification_details: null
viz_type: mapbox
params:
  all_columns:
  - occupancy
  all_columns_x: LON
  all_columns_y: LAT
  granularity_sqla: day
  mapbox_style: mapbox://styles/mapbox/light-v9
  row_limit: 500000
  since: '2014-01-01'
  until: now
  viz_type: mapbox
query_context: null
cache_timeout: null
uuid: f80c145e-5cfa-4cf8-82ac-39c456e542cf
version: 1.0.0
dataset_uuid: 9451efea-a5b0-4925-9ca3-59d445fff41b
