slice_name: New Members per Month
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  adhoc_filters: []
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  compare_lag: 1
  compare_suffix: MoM
  datasource: 66__table
  granularity_sqla: date
  header_font_size: 0.4
  metric:
    aggregate: SUM
    column:
      column_name: new_members
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1849
      is_dttm: false
      optionName: _col_New Members
      python_date_format: null
      type: BIGINT
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(New Members)
    optionName: metric_7pksdivmphp_bicn1fji7en
    sqlExpression: null
  queryFields:
    metric: metrics
  rolling_type: None
  show_trend_line: true
  slice_id: 3055
  start_y_axis_at_zero: true
  subheader_font_size: 0.15
  time_grain_sqla: P1M
  time_range: No filter
  url_params: {}
  viz_type: big_number
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 15, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "date", "filters": [], "extras": {"time_grain_sqla":
  "P1M", "having": "", "where": ""}, "applied_time_extras": {}, "columns": [], "metrics":
  [{"aggregate": "SUM", "column": {"column_name": "new_members", "description": null,
  "expression": null, "filterable": true, "groupby": true, "id": 1849, "is_dttm":
  false, "optionName": "_col_New Members", "python_date_format": null, "type": "BIGINT",
  "verbose_name": null}, "expressionType": "SIMPLE", "hasCustomLabel": false, "isNew":
  false, "label": "SUM(New Members)", "optionName": "metric_7pksdivmphp_bicn1fji7en",
  "sqlExpression": null}], "annotation_layers": [], "series_limit": 0, "order_desc":
  true, "url_params": {}, "custom_params": {}, "custom_form_data": {}, "is_timeseries":
  true, "post_processing": [{"operation": "pivot", "options": {"index": ["__timestamp"],
  "columns": [], "aggregates": {"SUM(New Members)": {"operator": "mean"}}, "drop_missing_columns":
  true}}, {"operation": "flatten"}]}], "form_data": {"datasource": "15__table", "viz_type":
  "big_number", "slice_id": 111, "granularity_sqla": "date", "time_grain_sqla": "P1M",
  "time_range": "No filter", "metric": {"aggregate": "SUM", "column": {"column_name":
  "new_members", "description": null, "expression": null, "filterable": true, "groupby":
  true, "id": 1849, "is_dttm": false, "optionName": "_col_New Members", "python_date_format":
  null, "type": "BIGINT", "verbose_name": null}, "expressionType": "SIMPLE", "hasCustomLabel":
  false, "isNew": false, "label": "SUM(New Members)", "optionName": "metric_7pksdivmphp_bicn1fji7en",
  "sqlExpression": null}, "adhoc_filters": [], "compare_lag": 1, "compare_suffix":
  "MoM", "show_trend_line": true, "start_y_axis_at_zero": true, "color_picker": {"a":
  1, "b": 135, "g": 122, "r": 0}, "header_font_size": 0.4, "subheader_font_size":
  0.15, "y_axis_format": "SMART_NUMBER", "time_format": "smart_date", "rolling_type":
  "None", "extra_form_data": {}, "dashboards": [9], "force": false, "result_format":
  "json", "result_type": "full"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 92e1d712-bcf9-4d7e-9b94-26cffe502908
version: 1.0.0
dataset_uuid: 9dd99cda-ff6b-4575-9a74-684d06e871ab
