slice_name: Participants
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  compare_lag: '5'
  compare_suffix: over 5Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__num
  row_limit: 10000000
  time_range: '100 years ago : now'
  viz_type: big_number
query_context: null
cache_timeout: null
uuid: a2c716de-9813-4436-bf57-1da7b3b73255
version: 1.0.0
dataset_uuid: b04f2fc3-ef74-44e8-9bd8-d1896ab9e59c
