slice_name: Pivot Table v2
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  groupbyColumns:
  - state
  groupbyRows:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 10000000
  time_range: '100 years ago : now'
  viz_type: pivot_table_v2
query_context: '{"datasource": {"id": 3, "type": "table"}, "queries": [{"columns":
  ["name", "state"], "metrics": ["sum__num"]}], "result_format": "json", "result_type":
  "full"}'
cache_timeout: null
uuid: ae20d6d4-96bb-4808-bedd-79464f9f2efe
version: 1.0.0
dataset_uuid: b04f2fc3-ef74-44e8-9bd8-d1896ab9e59c
