slice_name: Publishers With Most Titles
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 9__table
  viz_type: table
  slice_id: 102
  granularity_sqla: year
  time_grain_sqla: P1D
  time_range: No filter
  query_mode: raw
  groupby: []
  metrics:
  - count
  all_columns:
  - rank
  - name
  - global_sales
  - platform
  - genre
  - publisher
  - year
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 10
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  page_length: '2'
  show_cell_bars: false
  color_pn: false
  conditional_formatting: []
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource": {"id": 9, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "year", "filters": [], "extras": {"time_grain_sqla":
  "P1D", "having": "", "where": ""}, "applied_time_extras": {}, "columns": ["rank",
  "name", "global_sales", "platform", "genre", "publisher", "year"], "orderby": [],
  "annotation_layers": [], "row_limit": 10, "series_limit": 0, "order_desc": true,
  "url_params": {}, "custom_params": {}, "custom_form_data": {}, "post_processing":
  []}], "form_data": {"datasource": "9__table", "viz_type": "table", "slice_id": 102,
  "granularity_sqla": "year", "time_grain_sqla": "P1D", "time_range": "No filter",
  "query_mode": "raw", "groupby": [], "metrics": ["count"], "all_columns": ["rank",
  "name", "global_sales", "platform", "genre", "publisher", "year"], "percent_metrics":
  [], "adhoc_filters": [], "order_by_cols": [], "row_limit": 10, "server_page_length":
  10, "include_time": false, "order_desc": true, "table_timestamp_format": "smart_date",
  "page_length": "2", "show_cell_bars": false, "color_pn": false, "conditional_formatting":
  [], "extra_form_data": {}, "dashboards": [], "force": false, "result_format": "json",
  "result_type": "full"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: f30e8bd2-0016-4cfe-8207-97c125f98e62
version: 1.0.0
dataset_uuid: 53d47c0c-c03d-47f0-b9ac-81225f808283
