slice_name: Region Filter
description: null
certified_by: null
certification_details: null
viz_type: filter_box
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  date_filter: false
  entity: country_code
  filter_configs:
  - asc: false
    clearable: true
    column: region
    key: 2s98dfu
    metric: sum__SP_POP_TOTL
    multiple: false
  - asc: false
    clearable: true
    column: country_name
    key: li3j2lk
    metric: sum__SP_POP_TOTL
    multiple: true
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  row_limit: 10000000
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: filter_box
query_context: null
cache_timeout: null
uuid: 68bf8778-94fc-48ce-af69-12ee58b48b0e
version: 1.0.0
dataset_uuid: a430d917-f805-4fff-acb2-19135fa7b154
