slice_name: Top 10 Girl Name Share
description: null
certified_by: null
certification_details: null
viz_type: area
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  comparison_type: values
  granularity_sqla: ds
  groupby:
  - name
  limit: 10
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 10000000
  stacked_style: expand
  time_grain_sqla: P1D
  time_range: '100 years ago : now'
  viz_type: area
  x_axis_forma: smart_date
query_context: null
cache_timeout: null
uuid: 208f73c7-ed36-4f6a-9f3b-d5ce5d9d3bd0
version: 1.0.0
dataset_uuid: b04f2fc3-ef74-44e8-9bd8-d1896ab9e59c
