slice_name: Top 10 California Names Timeseries
description: null
certified_by: null
certification_details: null
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '10'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  row_limit: 10000000
  time_range: '100 years ago : now'
  timeseries_limit_metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  viz_type: line
query_context: null
cache_timeout: null
uuid: 242560f5-59ef-4417-a971-152df1a24548
version: 1.0.0
dataset_uuid: b04f2fc3-ef74-44e8-9bd8-d1896ab9e59c
