slice_name: Treemap
description: null
certified_by: null
certification_details: null
viz_type: treemap
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  - country_code
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 10000000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: treemap
query_context: null
cache_timeout: null
uuid: c677fb36-ac21-4471-82fb-a9a7c97844b2
version: 1.0.0
dataset_uuid: a430d917-f805-4fff-acb2-19135fa7b154
