slice_name: Weekly Messages
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  adhoc_filters: []
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  compare_lag: 1
  compare_suffix: WoW
  datasource: 34__table
  granularity_sqla: ts
  header_font_size: 0.4
  metric: count
  queryFields:
    metric: metrics
  rolling_type: None
  show_trend_line: true
  slice_id: 1905
  start_y_axis_at_zero: true
  subheader_font_size: 0.15
  time_grain_sqla: P1W
  time_range: No filter
  time_range_fixed: false
  url_params: {}
  viz_type: big_number
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 17, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "granularity": "ts", "filters": [], "extras": {"time_grain_sqla":
  "P1W", "having": "", "where": ""}, "applied_time_extras": {}, "columns": [], "metrics":
  ["count"], "annotation_layers": [], "series_limit": 0, "order_desc": true, "url_params":
  {}, "custom_params": {}, "custom_form_data": {}, "is_timeseries": true, "post_processing":
  [{"operation": "pivot", "options": {"index": ["__timestamp"], "columns": [], "aggregates":
  {"count": {"operator": "mean"}}, "drop_missing_columns": true}}, {"operation": "flatten"}]}],
  "form_data": {"adhoc_filters": [], "color_picker": {"a": 1, "b": 135, "g": 122,
  "r": 0}, "compare_lag": 1, "compare_suffix": "WoW", "datasource": "17__table", "granularity_sqla":
  "ts", "header_font_size": 0.4, "metric": "count", "queryFields": {"metric": "metrics"},
  "rolling_type": "None", "show_trend_line": true, "slice_id": 78, "start_y_axis_at_zero":
  true, "subheader_font_size": 0.15, "time_grain_sqla": "P1W", "time_range": "No filter",
  "time_range_fixed": false, "url_params": {}, "viz_type": "big_number", "y_axis_format":
  "SMART_NUMBER", "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: abe2c022-ceee-a60a-e601-ab93f7ee52b1
version: 1.0.0
dataset_uuid: e032c69e-716e-d700-eff7-07800d0f9989
