slice_name: World's Pop Growth
description: null
certified_by: null
certification_details: null
viz_type: area
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 10000000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: area
query_context: null
cache_timeout: null
uuid: 9670a51b-0d93-42f9-8a52-9efb30616ffc
version: 1.0.0
dataset_uuid: a430d917-f805-4fff-acb2-19135fa7b154
